### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZweiBR** [ppkantorski/Ultrahand-Overlay#103]
When changing the sequence of buttons to enter the Tesla menu I receive an error like this cracking

**Comment by ppkantorski** [comment]
I'm confused by the error you are referring to.  Can you please elaborate what you are trying to say a bit clearer?

**Comment by ZweiBR** [comment]
> I'm confused by the error you are referring to. Can you please elaborate what you are trying to say a bit clearer?
https://a.imagem.app/otOHuN.jpeg
https://a.imagem.app/otOSNC.jpeg
https://a.imagem.app/otOknY.jpeg

I apologize for my English, I speak a little
When changing the Tesla button sequence the error appears.

**Comment by ppkantorski** [comment]
If you manually set the key combo within the config.ini and it is not among the selection of combos, it will not show up within settings (although should still be functional).  If you choose one of the preset combos however it should display your combo there.

**Comment by ZweiBR** [comment]
> If you manually set the key combo within the config.ini and it is not among the selection of combos, it will not show up within settings (although should still be functional). If you choose one of the preset combos however it should display your combo there.
> 
> As for your crash, it's hard to tell what's going on. Just try again by deleting the /config/ultrahand/config.ini file and set your combo within settings. It's possible something within your config file is messed up.

config/ultrahand/config.ini 
Even deleting the file the error persists

**Comment by ZweiBR** [comment]
Problem resolved.
I changed the atmosphere custom package.

**Comment by sskyNS** [comment]
> 问题解决了。我改变了氛围定制套餐。
Like some kind of memory access error, it may not be so closely related to the actual atmosphere, because you restarted your machine once. Some conflicts exist in /ultrahand/config.ini. When you modify your configuration, there may be some errors when the memory accesses the data, which also exists in theme.ini.

**Comment by sskyNS** [comment]
In addition, pay attention to your plug-in combination. Sys-triplayer 420000000007E51A It seems that you need to update. Maybe it is not compatible with ultrahand (I think a similar problem exists in idn). In fact, you need to test it. I'm sorry that I only tested the former.
