### ISSUE TITLE
Ultrahand Menu starts lagging after some minutes

### ISSUE THREAD

**Issue by Kelvao** [ppkantorski/Ultrahand-Overlay#110]
When I power on my switch and open Ultrahand menu, he works smooth, but in some minutes he starts lagging. 
I tried remove some sysmodules and overlays but not make any difference.

When I power on my switch:

https://github.com/ppkantorski/Ultrahand-Overlay/assets/32245417/78fc1482-271b-4c22-99b8-142f9d5f2a54

After few minutes:

https://github.com/ppkantorski/Ultrahand-Overlay/assets/32245417/a65ad514-c50a-46ea-9dd9-e724aff0f7ad

**Comment by ZweiBR** [comment]
Taking advantage of the topic, how do I add themes?
Update your package to nx-ovlloader 1.0.7

**Comment by Kelvao** [comment]
same issue in 1.0.7

**Comment by Kelvao** [comment]
Same issue with the latest version.

**Comment by ZweiBR** [comment]
> When I power on my switch and open Ultrahand menu, he works smooth, but in some minutes he starts lagging. I tried remove some sysmodules and overlays but not make any difference.
> 
> When I power on my switch:
> 
>  IMG_3249.MOV 
> After few minutes:
> 
>  IMG_3249.2.MOV

Vc tá usando o pacote GNX ? mude para outro.
Are you using the GNX package? change to another.

I recommend BP.

**Comment by ppkantorski** [comment]
Sorry for not getting back to you sooner.  This issue isn't something I personally can reproduce so its kind of hard to assess what's going on here

**Comment by Kelvao** [comment]
> > When I power on my switch and open Ultrahand menu, he works smooth, but in some minutes he starts lagging. I tried remove some sysmodules and overlays but not make any difference.
> > When I power on my switch:
> > IMG_3249.MOV
> > After few minutes:
> > IMG_3249.2.MOV
> 
> Vc tá usando o pacote GNX ? mude para outro. Are you using the GNX package? change to another.
> 
> I recommend CNX.

Im using CNX, still having issues in the latest version
