### ISSUE TITLE
Bug: Overlays don't show up

### ISSUE THREAD

**Issue by Exor** [ppkantorski/Ultrahand-Overlay#111]
My overlays menu is blank. I was previously using Tesla on firmware 16.0.0 with the ovlEdiZon, ReverseNX-RT-ovl, and sys-clk-overlay overlays. After upgrading to firmware 17.0.0, Tesla was crashing Atmosphere so I installed the Ultrahand-Overlay instead. After finding the overlays menu blank, I tried installing the Edizon-overlay and FPSLocker through the included "Easy Installer" package to no avail. 

Launch-day switch
EmuMMC 17.0.0 firmware
Atmosphere 1.6.2
Hekate 6.1.0
nx-ovlloader 1.0.6
Ultrahand-Overlay 1.4.9

**Comment by Exor** [comment]
I updated to firmware 17.0.1 and still don't see any overlays. The *.ovl files are in the /switch/.overlays folder.

I installed the latest version of nx-ovlloader (1.0.7??) from github, but Ultrahand-Overlay displays version 1.0.6. Looking at the nx-ovlloader Makefile, it also shows "APP_VERSION	:=	1.0.6", so looks like a display mistake. Is there is a different 1.0.7 nx-ovlloader build somewhere?

**Comment by ZweiBR** [comment]
My system updated
17.01 with amosphere 162
Hekate 610
Switch OLED

https://a.imagem.app/oy3zKt.jpeg
https://a.imagem.app/oy32C0.jpeg
https://a.imagem.app/oy37ay.jpeg
https://a.imagem.app/oy3nzr.jpeg

**Comment by sskyNS** [comment]
@Exor Please use the latest version of Ultrahand, make sure your /Switch/overlays/ovlmenu.ovl is installed properly, and then check that your /atmosphere/contents/4200000000007E51A file exists and is in the correct path. If everything is in order, you shouldn't have such minor problems. Finally, happy play!

**Comment by sskyNS** [comment]
> 我的系统更新了 17.01 和 amosphere 162 Hekate 610 开关 OLED
> 
> https://a.imagem.app/oy3zKt.jpeg https://a.imagem.app/oy32C0.jpeg https://a.imagem.app/oy37ay.jpeg https://a.imagem.app/oy3nzr.jpeg
> 
> 我想知道作者：我如何应用主题？ https://a.imagem.app/oy30l2.jpeg

Regarding the application of themes, most of them use RGB444 color coding, which should be detailed on the wiki. The general operation method is given below, and the theme file is located in /config/ultrahand/themes/.. then all you need to do is turn on the machine, open UltraHand, then click [+], find the theme settings, select the theme you set, and it will understand that it will take effect, no need to restart the machine

**Comment by ZweiBR** [comment]
> > 我的系统更新了 17.01 和 amosphere 162 Hekate 610 开关 OLED
> > https://a.imagem.app/oy3zKt.jpeg https://a.imagem.app/oy32C0.jpeg https://a.imagem.app/oy37ay.jpeg https://a.imagem.app/oy3nzr.jpeg
> > 我想知道作者：我如何应用主题？ https://a.imagem.app/oy30l2.jpeg
> 
> Regarding the application of themes, most of them use RGB444 color coding, which should be detailed on the wiki. The general operation method is given below, and the theme file is located in /config/ultrahand/themes/.. then all you need to do is turn on the machine, open UltraHand, then click [+], find the theme settings, select the theme you set, and it will understand that it will take effect, no need to restart the machine

Thanks, it works great

**Comment by Exor** [comment]
I did a fresh install of atmosphere, hekate, nx-ovlloader, ultrahand, and switch-oc-suite on a blank SD card and it works.

**Comment by JonJaded** [comment]
Hey there, I just wanted to add that my sd/switch/ folder had a capital S from when I remoted in with my android (since it capitals first words) and was preventing my overlays from working. It just hit me after 2 hours of troubleshooting that it could be a problem! Everything works now.

**Comment by ppkantorski** [comment]
On linux you can have two separate folders simultaneously, `sdmc:/switch/` and `sdmc:/Switch/`.  On macOS and Windows, they have some stuff to prevent this from what i understand.  There is a general consensus on the usage of a lowercase folder name.
