### ISSUE TITLE
Doesn't write on atmosphere/contents directory

### ISSUE THREAD

**Issue by kevsestrella** [ppkantorski/Ultrahand-Overlay#112]
Hi, first of all, thank you for this awesome app. I'm trying to setup a package that moves(I've also tried copy) sysmodules to atmosphere/contents/.backup directory. I'm able to do this manually, say, with DBI's sdcard browser but testing things out, Ultrahand mv and cp seems to fail to write after cutting(mv) or copying(cp). I understand that atmosphere directory is special but just wondering if it's possible with Ultrahand since it's doable manually with other apps.

Here's the command I'm trying to run
```mv /atmosphere/contents/0000000000534C56 /atmosphere/contents/.backup/```

**Comment by sskyNS** [comment]
i think that u need write like these:"mv /atmosphere/contents/0000000000534C56/

**Comment by kevsestrella** [comment]
> i think that u need write like these`mv /atmosphere/contents/0000000000534C56/` Other example like: `del /atmosphere/contents/00FF0000636C6BFF/`

Thanks, with your comment, I understand it now 😄. The correct command to what I want is 

```mv /atmosphere/contents/0000000000534C56/ /atmosphere/contents/.backup/0000000000534C56/```

I'll close this now.
