### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by HookedBehemoth** [ppkantorski/Ultrahand-Overlay#113]
I just saw that this project lifted big parts of it's reboot logic from hekate, atmosphere and studious pancake which are all GPLv2 licensed. The license you chose for this project isn't compatible with the GPL Software License. See https://www.gnu.org/licenses/license-list.en.html#ccbysa

**Comment by ppkantorski** [comment]
The GPLv2 code is used separately from the CC BY-NC 4.0 material.  Please keep that in mind.  There is code in the project that is of a public license, code that isn't.  I made sure to give you credit as well, but do know that not all code included is of the same license.

**Comment by ppkantorski** [comment]
For that code, I did not change the license intentionally for this very reason.

**Comment by HookedBehemoth** [comment]
Hey,
This is fundamentally not how interactions with the GPL class of licenses work. You can read up on it in the licensing terms themselves or under this point in the FAQ https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL
I recommend you release your code that links against libtesla, sp, Atmosphère and hekate code under the GPLv2. If you don't have the rights to do so, please stop distributing binaries.

**Comment by WerWolv** [comment]
Behemoth is absolutely correct here. libtesla is under GPLv2 and you're statically linking that into your binary which requires the entire code that interfaces with it to be under GPLv2 as well.
Probably the only thing you're allowed to have under your current license are assets, everything else needs to follow libtesla's license and the license of all other projects you lifted code from.

**Comment by ppkantorski** [comment]
I see you point now.  So I _believe_ that now I may need to make it explicit in code is not being statically linked or using methods directly from either libraries under my license (assets), and which code is not and must fall under GPLv2.  I appreciate the clarification, it was indeed something I overlooked. Also, I really appreciate your work. libTesla was a lot of fun to play with last year, as well as everything else you've made.

> Behemoth is absolutely correct here. libtesla is under GPLv2 and you're statically linking that into your binary which requires the entire code that interfaces with it to be under GPLv2 as well. Probably the only thing you're allowed to have under your current license are assets, everything else needs to follow libtesla's license and the license of all other projects you lifted code from.

**Comment by ppkantorski** [comment]
> Hey, This is fundamentally not how interactions with the GPL class of licenses work. You can read up on it in the licensing terms themselves or under this point in the FAQ https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL I recommend you release your code that links against libtesla, sp, Atmosphère and hekate code under the GPLv2. If you don't have the rights to do so, please stop distributing binaries.

I will change the license for the binary to match GPLv2 (which does make sense), but i will preserve my own license on my code not directly statically linked to yours or WerWolv's.  I do not intend on redistributing binaries that do not fall under GPLv2, but my front page "license" may indeed be misleading since some derivative materials are being used.  Again, the point of me using additional licenses was not to overwrite GPLv2 or its existing protections.

**Comment by HookedBehemoth** [comment]
> but i will preserve my own license on my code not directly statically linked to yours or WerWolv
All the code in this repository statically links to GPLv2 code.
I don't get where you see a boundary here. You are obliged to share all this code to your users under the GPLv2.

**Comment by ppkantorski** [comment]
not all code is statically linked.  lots of code are custom functions i wrote myself.

> > but i will preserve my own license on my code not directly statically linked to yours or WerWolv
> 
> All the code in this repository statically links to GPLv2 code. I don't get where you see a boundary here. You are obliged to share all this code to your users under the GPLv2.

**Comment by WerWolv** [comment]
This is not how the GPL works. You're using libtesla (which is under GPLv2) in various files to fulfill the Overlay's purpose. Any code that interfaces with GPL code is required to be under the same GPL license as well. And that condition propagates through your entire program. Every function that will ultimately call any function in libtesla needs to be under the GPL license which is every single one of them in one way or another (not that you generally put a license on individual functions).

> Think of it like this. Even 100% without any of your's or WerWolv's code, my program will still function when being ran on the command line and could still "potentially" be used on any computer

Without libtesla, your overlay in the current state wouldn't be able to run at all. If you reimplemented libtesla from scratch though, you could obviously put it under any license you want. But you chose to link to libtesla which in turn requires you to follow its license. You can read about this specifically in subsection 2b of the GPLv2 license:
```
You must cause any work that you distribute or publish, that in whole or in part contains
or is derived from the Program or any part thereof, to be licensed as a whole at no charge
to all third parties under the terms of this License. 
```
https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by ppkantorski** [comment]
That is incorrect.  my download functions, hex functions, ini functions.. many of them can be ran on my mac with no need for an overlay or a nintendo switch.

> This is not how the GPL works. You're using libtesla (which is under GPLv2) in various files to fulfill the Overlay's purpose. Any code that interfaces with GPL code is required to be under the same GPL license as well. And that condition propagates through your entire program. Every function that will ultimately call any function in libtesla needs to be under the GPL license which is every single one of them in one way or another (not that you generally put a license on individual functions).
> 
> > Think of it like this. Even 100% without any of your's or WerWolv's code, my program will still function when being ran on the command line and could still "potentially" be used on any computer
> 
> Without libtesla, your overlay in the current state wouldn't be able to run at all. If you reimplemented libtesla from scratch though, you could obviously put it under any license you want. But you chose to link to libtesla which in turn requires you to follow its license. You can read about this specifically in subsection 2b of the GPLv2 license:
> 
> ```
> You must cause any work that you distribute or publish, that in whole or in part contains
> or is derived from the Program or any part thereof, to be licensed as a whole at no charge
> to all third parties under the terms of this License. 
> ```
> 
> https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by WerWolv** [comment]
Of course some of your individual functions would run fine without libtesla. But they're still part of the whole executable. 
You could put those utility functions under some other library that's compatible with GPLv2 and statically link to that. But each and every file that interfaces with libtesla or contains any Atmosphere code or code from Behemoth's libraries needs to be under the GPLv2. In its current state you're clearly violating the license.

**Comment by ppkantorski** [comment]
> Of course some of your individual functions would run fine without libtesla. But they're still part of the whole executable. You could put those utility functions under some other license that's compatible with GPLv2 and statically link to that. But each and every file that interfaces with libtesla or contains any Atmosphere code or code from Behemoth's libraries needs to be under the GPLv2. In its current state you're clearly violating the license.

"..each and every file that interfaces with libtesla or contains any Atmosphere code or code from Behemoth's libraries.."
That is correct.  However like I have stated, some of your guys' code interfaces with my code, not the other way around.  I could pull out functions and seperate them into my own custom library.

**Comment by WerWolv** [comment]
From what I can see the main offenders currently are:
https://github.com/ppkantorski/Ultrahand-Overlay/blob/main/source/main.cpp: Links to libtesla
https://github.com/ppkantorski/Ultrahand-Overlay/blob/main/source/utils.hpp: Uses code from Behemoth's util.hpp and payload.hpp as well as libtesla

The small helper files can be under any license you want, provided it is compatible with the GPLv2 license. But the vast majority of your project needs to be under GPLv2.

**Comment by ppkantorski** [comment]
> From what I can see the main offenders currently are: https://github.com/ppkantorski/Ultrahand-Overlay/blob/main/source/main.cpp: Links to libtesla https://github.com/ppkantorski/Ultrahand-Overlay/blob/main/source/utils.hpp: Uses code from Behemoth's util.hpp and payload.hpp as well as libtesla
> 
> The small helper files can be under any license you want, provided it is compatible with the GPLv2 license. But the vast majority of your project needs to be under GPLv2.

yes, there are indeed sections within main and utils that need to be modified.  I do agree.  as for helper functions, yes I can choose my own license.  I will make these changes very soon to remove further confusion.

**Comment by WerWolv** [comment]
Thank you.

**Comment by ppkantorski** [comment]
> Thank you.

again, both of you.  I really appreciate everything you guys have done. 🙏🏼. And I am sorry that my misguided use of licenses caused this issue.  It will be resolved.

**Comment by ppkantorski** [comment]
One other issue that arrises is the distribution of CC-by-NC-4.0 material directly within GPLv2 since in general these licenses can conflict.   I may have to compile each separately, or change CC-by-NC-4.0 in some way.  This is what I will try to resolve next, but it does indeed cause some room for confusion.

**Comment by ppkantorski** [comment]
I could create function .elf's, have the .ovl load them separately, but it seems like a hassle, especially since I did donated some functions to Masagrator in the past for Status Monitor.  I'll switch to [CC BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/) instead for this code.  That way it should retain compatibility.

**Comment by HookedBehemoth** [comment]
Please check what static compilation means and how the switch build chain works.

**Comment by ppkantorski** [comment]
> Please check what static compilation means and how the switch build chain works.

Sure I will, but again, since my project is now compliant with GPLv2, I appear to have circumvented any prior issues with my initial choice of license.   All code will fall under GPLv2 moving forward, but assigning my own license within the scope of the what is allowed under GPLv2 as a dual license removes any of the prior concerns that were raised.

**Comment by ppkantorski** [comment]
Alright, all GPLv2 derivative work is now solely GPLv2, but some of the non-derivative work will fall under CC-BY-4.0.  This license is compatible with GPLv2 distributions as long as its terms are met within the CC-BY-4.0 derivative work (here being the GPLv2 code).

**Comment by ppkantorski** [comment]
Thanks again both of you.  I appreciate the feedback on getting my project GPLv2 compliant.  Hopefully everything is resolved now, but feel free to add more comments or re-raise the issue in the future if there is anything else of concern.
