### ISSUE TITLE
The language files were downloaded to the wrong path

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [ppkantorski/Ultrahand-Overlay#115]
I downloaded them through the overlay, It seems that they have been placed in a deeper directory:
/config/ultrahand/lang/lang/*.json

**Comment by ppkantorski** [comment]
Thanks for bringing this to my attention.  I will examine what is going on and try to resolve it.

**Comment by ppkantorski** [comment]
I believe I know what the issue is now.  I will fix it.

**Comment by Heartbeat-Heartbreak** [comment]
It's okay now. Let me close it!
