### ISSUE TITLE
Hope to add touch support

### ISSUE THREAD

**Issue by nangongjing1** [ppkantorski/Ultrahand-Overlay#119]
I'd like to be able to use the package I added by touching the screen of the switch directly with my finger when opening the UltraHand menu.This will make Ultrahand more user-friendly and cool.

**Comment by ppkantorski** [comment]
It is already implemented, but I have yet to update to v1.5.1.  Next release will include full touch support.

**Comment by nangongjing1** [comment]
> It is already implemented, but I have yet to update to v1.5.1. Next release will include full touch support.

Cool
