### ISSUE TITLE
Hotkey not accepted

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [ppkantorski/Ultrahand-Overlay#161]
im trying to set my ultrahand hotkeys to this: "key_combo=L3+R3"
but it just doesnt work
i have no idea why it wont take it.

i basically want to press both my analog sticks to launch ultrahand, like i did with the tesla overlay

![configini](https://github.com/user-attachments/assets/f6de962c-5190-44a4-bf3b-4532be0ba89c)

**Comment by ppkantorski** [comment]
have you tried setting it from the settings menu?

**Comment by VorgonBattlecruiser** [comment]
That worked! Sorry about that mistake, didnt even occur to me that they might be referred to differently here!
