### ISSUE TITLE
Base Config.ini not being generated in switch/.packages

### ISSUE THREAD

**Issue by zrm9901** [ppkantorski/Ultrahand-Overlay#171]
Idk if this is correct, but from what I can  tell from the updates, there is supposed to be a autogenerated config.ini package generated in .packages containing basic commands, but it doesnt seem to generate for me, idk if I am doing something wrong but I cant seem to find the basic copy, delete, ect commands in the overlay menu or anywhere else. If there isnt a generated one how do I do the commands?

**Comment by ppkantorski** [comment]
Ah, I know exactly what you are referring to.  I appear to have forgotten to use a "true" statement on `loadOptionsFromIni` to generate it.  For now make this file in `/switch/.packages/package.ini`

`[*Reboot To]
[*Boot Entry]
ini_file_source /bootloader/hekate_ipl.ini
filter config
reboot boot '{ini_file_source(*)}'
[Hekate]
reboot HEKATE
[Hekate UMS]
reboot UMS

[Commands]
[Shutdown]
shutdown
`

**Comment by zrm9901** [comment]
okay thank you

**Comment by ppkantorski** [comment]
Should now be fixed in v1.7.0.  I am going to close this, but if there are still more problems related to this do lmk.
