### ISSUE TITLE
Variables do not work

### ISSUE THREAD

**Issue by do-kiss** [ppkantorski/Ultrahand-Overlay#177]
Hello, I tested version 1.7.1, and the four newly added variables ({ram_vendor}, {ram_model}, {ams_version}, and {hos_version}) are not working.

**Comment by do-kiss** [comment]
The "refresh wallpaper" command also didn't work. After using this command, I still had to exit Ultrahand and reopen it to see the background image refresh.**

**Comment by ppkantorski** [comment]
ah crap lol i think i see where I went wrong.  I put it in the source replacement rather than the standard placeholder replacement section.  as for refresh wallpaper, i think i also see the problem.

give me a sec, i'll try to quickly fix this.

**Comment by ppkantorski** [comment]
Should be fixed now.  Feel free to test it out

**Comment by do-kiss** [comment]
Thank you! I have an idea: can Ultrahand support a feature for uploading files to a URL? It would be great if a variable could be specified as a parameter for the upload command (such as the device serial number or any other unique identifier for the current device). I want to create an online backup plugin, but I need to avoid the misuse of the file upload API.

**Comment by ppkantorski** [comment]
I actually intentionally left uploading out.  This was done as a security precaution in the past.

However I did make this project as well for creating backups of files and pictures to your computer directly from your switch using ftp.
https://github.com/ppkantorski/Switch-FTP-Sync

**Comment by do-kiss** [comment]
Yeah, I saw it. It seems to only support use within a local network. It would be even better if it could support uploading to a public IP. I have a server that can provide storage space and an API interface for uploads.

**Comment by ppkantorski** [comment]
If you setup port forwarding, you can technically use switch-fip-sync with an external network.  But for a provider, yeah there's just a reason i'm not doing that right now. I may revisit this idea again in the future, but for now, I have more reasons to not implement this feature than to implement it.

**Comment by ppkantorski** [comment]
With this issue I assume resolved, I will be closing with this comment.  Thanks again, I appreciate you bringing it to my attention.
