### ISSUE TITLE
Scroll in table mode

### ISSUE THREAD

**Issue by cucholix** [ppkantorski/Ultrahand-Overlay#189]
Scroll in table mode only can be triggered with touch controls, I think table mode only accept 20 lines max, anything higher needs to be scrolled down.

![7DA14605-80D8-45E6-AFD7-FFD9D8BA6EDF](https://github.com/user-attachments/assets/dbcf1758-86e4-42f6-bcb3-c61fc259aaf9)

**Comment by ppkantorski** [comment]
btw you can modify the spacing using `;spacing=` for the tables.  For proper scrolling with controllers with tables, I have an idea of what i can do to make it work properly, but it will take a little work to make properly.

**Comment by ppkantorski** [comment]
Nearly got it complete now.  Theres just a few extra touches i need to add, then i have to clean up the implementation a tad.

**Comment by ppkantorski** [comment]
Issue is currently resolved on the `dev` fork for v1.7.7, but is currently being tested and reviewed.

**Comment by ppkantorski** [comment]
Issue has now been resolved in [v1.7.7](https://github.com/ppkantorski/Ultrahand-Overlay/releases/tag/v1.7.7).
