### ISSUE TITLE
Allow move to overwrite

### ISSUE THREAD

**Issue by monstrosities** [ppkantorski/Ultrahand-Overlay#2]
Hello,

Can you adjust `move` to overwrite files? I've observed that move will not work if the file exists on the destination path. This would simplify some commands that would currently require a copy followed by a delete. Thanks!

**Comment by monstrosities** [comment]
Thanks. I also noticed that if I try and use `move` instead of `copy` + `del` to toggle a directory then it recursively moves files inside the directory instead of the directory itself which breaks the toggling. `copy` + `del` is fine for small files but it's too slow for toggling something large that a `move` could do instantly.

To give the example I changed:
```
[*exeFS Patches]
filter_on /atmosphere/exefs_patches/.offload/
source_on /atmosphere/exefs_patches/*/
mkdir /atmosphere/exefs_patches/.offload/
copy {source_on} /atmosphere/exefs_patches/.offload/
del {source_on}

source_off /atmosphere/exefs_patches/.offload/*/
copy {source_off} /atmosphere/exefs_patches/
del {source_off}
```

To:
```
[*exeFS Patches]
filter_on /atmosphere/exefs_patches/.offload/
source_on /atmosphere/exefs_patches/*/
mkdir /atmosphere/exefs_patches/.offload/
move {source_on} /atmosphere/exefs_patches/.offload/

source_off /atmosphere/exefs_patches/.offload/*/
move {source_off} /atmosphere/exefs_patches/
```

If you could correct the behavior or tell me if I've made a mistake that would be great.

**Comment by ppkantorski** [comment]
Move should overwrite now.  As for filters, I still wanna work on that a bit more.  Yes right now it only allows for single line filters, but i'll see what I can do to implement more features and update the documentation over time.

**Comment by ppkantorski** [comment]
Ive updated the example for Mod Master and implemented the feature.  Going to close this issue for now.
