### ISSUE TITLE
Ultrahand Won’t Show If “Adjust Screen Size” Is Not 100%

### ISSUE THREAD

**Issue by FunkSmugly** [ppkantorski/Ultrahand-Overlay#200]
I wanted to see if a fix would be implementable for an issue that has persisted with Tesla; Adjust Screen Size (overscan). Ultrahand will not show up in games if the Adjust Screen Size setting of the console is not at 100%.

**Comment by ppkantorski** [comment]
This is an old problem with libtesla that affects every overlay.  I'll look into it though to see if I can address it at all.

**Comment by ppkantorski** [comment]
If I do fix it btw, this problem will still be present in every single Tesla overlay.

**Comment by FunkSmugly** [comment]
I realize it is an inherited problem and not an issue with Ultrahand. I didn't know that it would persist with each overlay even if fixed. Please, don't feel obligated to look into this over other planned projects and updates. You've given us all plenty to be satisfied with. Thanks.

**Comment by ppkantorski** [comment]
I actually fixed it. (atleast for Ultrahand / my custom libTesla + libUltra)

Since my fork of libtesla + libultra can also be used to build overlays, I thought it might be useful.   I'll add this fix to the next revision.

**Comment by FunkSmugly** [comment]
Thank you! I’ve always regretted not learning to code. Being able to write it is a remarkable skill, although troubleshooting someone else’s work is just incredible. Thanks again!
