### ISSUE TITLE
Unreliable calling {index} {value} in trackbar

### ISSUE THREAD

**Issue by gczark** [ppkantorski/Ultrahand-Overlay#207]
I'm trying to create a very short script to adjust my clocks, trackbar sending incorrect {values} usually when user inputs are quick or ultrahand is immediately closed.

```
[Profiles]
;mode=named_step_trackbar
;unlocked=true
list_source '(Official, Erista, Mariko)'
;delete /config/sys-clk/config.ini
copy /scripts_user/{value}.ini /config/sys-clk/config.ini
```

and how can I convert this to an overlay?

**Comment by ppkantorski** [comment]
I think you can use the placeholder
```{list_source({value})}```

Let me know if this works for you.

**Comment by gczark** [comment]
same issue

it feels like when I switch from 1st to 3rd index very quickly, the 3rd is ignored because the script for the 2nd is still running.

when I pause for 2nd (assuming the script finishes) and then to 3rd for about a second. I get the 3rd profile correctly.

**Comment by ppkantorski** [comment]
hmm maybe try `{list_source({index})}` or `{list_source(*)}`.  I'd have to test it out again when i get the chance.  you can always add the command `logging` to the start of your commands then check the `log.txt` generated your package folder.

This shouldnt be that difficult, but its possible I may have overlooked something.

**Comment by ppkantorski** [comment]
```
iii. Named step track-bar is called utilizing ;mode=named_step_trackbar.

Requires a list_source definition or a list_file_source definition (for loading the names).
Does not use ;min_value=, ;max_value=, ;units=, nor ;steps=.
All track-bars commands can be used with placeholders {value} for returning the value and {index} for returning the index. Both value and index are also stored within the package config.ini file according to the track-bar entry.
```

**Comment by gczark** [comment]
there is a noticeable improvement when using `{list_source(*)}`, or it is just me.

also can confirm that when I switch from 1st to 3rd index, the script also runs for the 2nd which is not preferred behavior. Is there any way to only execute the script after the selection is confirmed (may not possible when using the `unlocked` flag)?

```
[2024-10-05 23:07:43] Executing command: list_source (Official, Erista, Mariko) 
[2024-10-05 23:07:43] Executing command: delete /config/sys-clk/config.ini 
[2024-10-05 23:07:44] Executing command: copy /scripts_user/Erista.ini /config/sys-clk/config.ini 
[2024-10-05 23:07:44] Executing command: list_source (Official, Erista, Mariko) 
[2024-10-05 23:07:44] Executing command: delete /config/sys-clk/config.ini 
[2024-10-05 23:07:44] Executing command: copy /scripts_user/Mariko.ini /config/sys-clk/config.ini 

```

and the question about `option` as alternative, this is how it looks like:
![image](https://github.com/user-attachments/assets/956c9a4c-7ba6-4894-9857-e229c3f7ca53)

**Comment by ppkantorski** [comment]
I can make a new feature for locked trackbars to "apply changes on lock".  maybe something like `;on_lock=true`.

As for how you are using the dropdown command,  you are missing the wildcard parameter.  And you cant use `{index}` on anything but trackbars.  youll need to use `{list_source(*)}`. Also, `;unclocked=` is only a parameter for trackbars as well.

```
[*Profiles]
;mode=option
logging
list_source '(Official, Erista, Mariko)'
delete /config/sys-clk/config.ini
copy /scripts_user/{list_source(*)}.ini  /config/sys-clk/config.ini
```

The `*` in the command name tells the method that this command will draw a new page (dropdown menu).  Then the `*` in placeholders is used as the index in this case. (see [Example](https://github.com/ppkantorski/Mod-Alchemist/blob/main/Mod%20Alchemist/package.ini))

I will actually need to update the documentation more because some of the specifics may have been left out.  But do look over the Ultrahand packages already made for guidance.

**Comment by ppkantorski** [comment]
Some additional details.  If it has the word "source" in the placeholder and it is not a TrackBar, the command name will require a `*` at the start.  This will also tell users that it is not a regular command, but a vector/list of commands.

**Comment by ppkantorski** [comment]
Did `;on_every_tick=true` resolve your original trackbar issue btw? (which executes on every tick)

I am going to close this issue in the coming days.  Hopefully everything you were working on is functional now.

**Comment by gczark** [comment]
> Did `;on_every_tick=true` resolve your original trackbar issue btw? (which executes on every tick)

I tried and the issue still persists. Decided to stick with `mode=option`.

**Comment by ppkantorski** [comment]
i rearead your comments.  i think i understand better now what you were trying to say.  i'll look more into it

**Comment by ppkantorski** [comment]
> same issue
> 
> it feels like when I switch from 1st to 3rd index very quickly, the 3rd is ignored because the script for the 2nd is still running.
> 
> when I pause for 2nd (assuming the script finishes) and then to 3rd for about a second. I get the 3rd profile correctly.
> 
> also, I try using `option` as alternative, but the list_source is not initializing.

how are you shifting indexes by the way? are you doing rapid clicks? click and hold? or touch?

**Comment by ppkantorski** [comment]
Ok actually I think i fixed the issue you are describing now.

**Comment by ppkantorski** [comment]
ill test out your exact usage case and try to see what i can do to fix it

**Comment by ppkantorski** [comment]
Think i made a typo.  perhaps try this one.
[ovlmenu.zip](https://github.com/user-attachments/files/17335912/ovlmenu.zip)

Will test your package soon.

**Comment by ppkantorski** [comment]
Ok been playing with it for a bit.  Feels like I fixed it for the most part.
[ovlmenu.zip](https://github.com/user-attachments/files/17338815/ovlmenu.zip)

**Comment by ppkantorski** [comment]
[ovlmenu.zip](https://github.com/user-attachments/files/17338902/ovlmenu.zip)
ok i *think* I fixed it now.  feel free to try it out

**Comment by ppkantorski** [comment]
I figured out the source of your problem.  You are modifying `/config/sys-clk/config.ini` which is being read / used directly by sys-clk in real time.  This occasionally can cause conflicting when trying to overwrite the file.  This is why I was seeing in consistent results.  I did try to tighten up the methods though and mitigate the problem a bit, but what it comes down to is the nature of what is being updated here.  I also decided to add a click feature to track bars so that you can click it to apply the setting. 

here's the version im playing with rn.
[ovlmenu.zip](https://github.com/user-attachments/files/17341800/ovlmenu.zip)

**Comment by gczark** [comment]
> [ovlmenu.zip](https://github.com/user-attachments/files/17342147/ovlmenu.zip) (update 4:50 AM PST)

There are still hiccups, and yup maybe because it is still on read. But there's a large improvement.

Also a minor visual glitch was fixed. The blue background on the selection after trackbar is locked is now gone. (this can be seen on the video)

**Comment by ppkantorski** [comment]
yeah i fixed a number of things.  that visual glitch was just the copy percentage not resetting. what i did was try to add some retries, but even when the retry attempt claims it was successful after X number of retries, sometimes the file ends up not being modified.  I tried this with a different file path, and i never once had to even trigger a retry attempt.

**Comment by ppkantorski** [comment]
All these issues appear to be addressed, and the fixes for trackbars will be released in the next version of Ultrahand.  With that in mind, i will be closing this issue for now.  New version should be coming soon in the coming days.
