### ISSUE TITLE
All games are now corrupted

### ISSUE THREAD

**Issue by Deaddnee** [ppkantorski/Ultrahand-Overlay#212]
After installing ultrahand, all of my games won't launch, stating that the data is corrupted

**Comment by Deaddnee** [comment]
trying to reinstall tinfoil isn't doing anything either
seems to just be games ripped from carts (?!)

**Comment by ppkantorski** [comment]
This has nothing to do with ultrahand and is likely because you updated Atmosphere.

**Comment by Deaddnee** [comment]
yeah, i updated atmosphere before installing ultrahand and this hadn't happened then

**Comment by ppkantorski** [comment]
If you look up your issue online, I'm sure you'll figure it out.  But this issue isn't something that should be discussed here.
