### ISSUE TITLE
Could you explain me the Easy Installer overlays.json please?

### ISSUE THREAD

**Issue by HeikesFootSlave** [ppkantorski/Ultrahand-Overlay#213]
Hello ppkantorski,

I just realised 2-3 Days ago how GENIUS your App is!

I started to read the Wiki and try to understand the packages, looking at the examples you made!

What I don't understand is how the overlay.json is working from the Easy Installer Package?
If I look at this as example:
{
        "name": "EdiZon - latest",
        "zip-url": "https://api.github.com/repos/proferabg/EdiZon-Overlay/releases?per_page=1&sort=created&order=desc",
        "download-entry": "0"
    },

zip-url and ovl-url is clear for me (package.ini), but if I open the link from "zip-url" in a browser and see that file with lots of entries I don't know which is the "download-entry": "0"?

And in case of OC Suite and sysDVR it is download-entry 1 and the other is 3!

If I want to put more entries into that file like BootSoundNX from TheModdersDen what do I have to do?
If I do it like you in that file I have this URL: https://api.github.com/repos/TheModdersDen/BootSoundNX/releases?per_page=1&sort=created&order=desc

Which download entry would that be?
And here is a bigger Problem = The 1.4.0 beta is still broken but the 1.3.0 works = how to get that file?

Sorry for so many questions!

THANK YOU in advance and greetings from Germany!

**Comment by ppkantorski** [comment]
Here download-entry corresponds to the file index in the list within the json file.  Some projects package multiple files.  zip-url here tells the package that the download / install type is a .zip so it should follow the zip instructions, and download entry is 0 so the first file it refers to is the .zip file.  In the case of BootSoundNX, entry 0 corresponds to

```json
      {
        "url": "https://api.github.com/repos/TheModdersDen/BootSoundNX/releases/assets/101972914",
        "id": 101972914,
        "node_id": "RA_kwDOF4KTuc4GE_uy",
        "name": "BootSoundNX-1.4.0-beta.zip",
        "label": null,
        "uploader": {
          "login": "TheModdersDen",
          "id": 3487232,
          "node_id": "MDQ6VXNlcjM0ODcyMzI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3487232?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/TheModdersDen",
          "html_url": "https://github.com/TheModdersDen",
          "followers_url": "https://api.github.com/users/TheModdersDen/followers",
          "following_url": "https://api.github.com/users/TheModdersDen/following{/other_user}",
          "gists_url": "https://api.github.com/users/TheModdersDen/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/TheModdersDen/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/TheModdersDen/subscriptions",
          "organizations_url": "https://api.github.com/users/TheModdersDen/orgs",
          "repos_url": "https://api.github.com/users/TheModdersDen/repos",
          "events_url": "https://api.github.com/users/TheModdersDen/events{/privacy}",
          "received_events_url": "https://api.github.com/users/TheModdersDen/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-zip-compressed",
        "state": "uploaded",
        "size": 339624,
        "download_count": 253,
        "created_at": "2023-04-02T06:54:38Z",
        "updated_at": "2023-04-02T06:54:38Z",
        "browser_download_url": "https://github.com/TheModdersDen/BootSoundNX/releases/download/1.4.0/BootSoundNX-1.4.0-beta.zip"
      }
```
where it will then use `browser_download_url` for this 0th index to download the zip file.

**Comment by HeikesFootSlave** [comment]
In case of BootSoundNX I have to use this url to get all releases:
https://api.github.com/repos/TheModdersDen/BootSoundNX/releases

And to get BootSoundNX 1.3.0 I have to set "download_entry" = "1"

Correct?

**Comment by ppkantorski** [comment]
You will use 0 for the 0th/1st index,  1 for the 2nd index, etc.

**Comment by ppkantorski** [comment]
hope your concerns were addressed.  going to be closing this issue.

**Comment by HeikesFootSlave** [comment]
Don't wanted to open new Issue!

I want to download some extra apps and extended the package.ini of Easy Installer and made a extra file called "nro.json"

Part of package.ini for extra Apps (mostly nro files):
`[*Installiere Zusatzapps]
json_file_source '/switch/.packages/Easy Installer/nro.json' name

try:
delete /config/ultrahand/downloads/zip-url.json
download {json_file_source(*,zip-url)} /config/ultrahand/downloads/zip-url.json
json_file /config/ultrahand/downloads/zip-url.json
download {json_file(0,assets,{json_file_source(*,download-entry)},browser_download_url)} /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
unzip /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)} /config/ultrahand/downloads/zip-url/
move /config/ultrahand/downloads/zip-url/ /switch/{json_file_source(*,ordner)}/
delete /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
delete /config/ultrahand/downloads/zip-url.json

try:
delete /config/ultrahand/downloads/zip-url-version.json
download {json_file_source(*,zip-url-version)} /config/ultrahand/downloads/zip-url-version.json
json_file /config/ultrahand/downloads/zip-url-version.json
download {json_file(assets,{json_file_source(*,download-entry)},browser_download_url)} /config/ultrahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)}
unzip /config/ultrahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)} /config/ultrahand/downloads/zip-url-version/
move /config/ultrahand/downloads/zip-url-version/ /switch/{json_file_source(*,ordner)}/
delete /config/ultrahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)}
delete /config/ultrahand/downloads/zip-url-version.json

try:
; for if file is .nro
delete /config/ultrahand/downloads/nro-url.json
download {json_file_source(*,nro-url)} /config/ultrahand/downloads/nro-url.json
json_file /config/ultrahand/downloads/nro-url.json
download {json_file(0,assets,{json_file_source(*,download-entry)},browser_download_url)}  /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
mv /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)} /switch/{json_file_source(*,ordner)}/
delete /config/ultrahand/downloads/nro-url.json`

If I have a file and it's been downloaded as zip
then I unzip it and get a folder with some folders in it like (atmosphere, config and switch)

How can I move all of it into the root of the SD?

The BootSoundNX App I mentioned above has = atmosphere and config folder in it

`mv /config/ultrahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)} /`

Is "/" the root of the SD or the ".package" folder in switch?

How to declare the root of the SD?

SORRY for disturbing you with that shit!

**Comment by ppkantorski** [comment]
`./` is the folder where the package ini file is being ran. SD card root is `/` or `sdmc:/`.

**Comment by HeikesFootSlave** [comment]
And another dumb question :(

On your repo is a "themes" folder but I don't know where to put it or how to use it?

I placed the whole folder "themes" into /config/UltraHand/themes, also in /themes/ but doesn't work!

PS Opened a Pull Request fo german translation to give you something back :)

**Comment by ppkantorski** [comment]
Many of the themes need updating, but you add the theme ini files to the `/config/ultrahand/themes/` folder.  Then you can select them from the settings menu.

**Comment by HeikesFootSlave** [comment]
Copied all the "themename.ini" files directly into `/config/UltraHand/themes` but with no luck!

UltraHand always shows the standard one alone :(

Do I have to choose one and rename it to theme.ini and overwrite the one made in `/config/UltraHand` ?

The Standard Theme created by UltraHand in `/config/UltraHand` is good to use as "base" (you said some have to be updated)

**Comment by ppkantorski** [comment]
maybe the folder name is incorrect.  it should all be lower case
