### ISSUE TITLE
System Commands

### ISSUE THREAD

**Issue by ZweiBR** [ppkantorski/Ultrahand-Overlay#215]
Hello, is there a command to update the modules? For example, Status Monitor Overlay 1.1.6, if I update to Status Monitor Overlay 1.1.7, is it possible to update with just one click?

**Comment by ppkantorski** [comment]
See [Easy Installer](https://github.com/ppkantorski/Ultrahand-Overlay/tree/main/examples/Easy%20Installer).

**Comment by ZweiBR** [comment]
thank you very much
