### ISSUE TITLE
Leftover move issue

### ISSUE THREAD

**Issue by monstrosities** [ppkantorski/Ultrahand-Overlay#4]
Hello,

About issue https://github.com/ppkantorski/Ultrahand-Overlay/issues/2

The second issue I described still exists, I noticed you updated your [example ](https://github.com/ppkantorski/Ultrahand-Overlay/tree/main/examples/Mod%20Master) to match the one I posted but that's exactly where the problem is.

To summarize again:

`move` used like this recursively moves files inside the directory instead of the directory itself which breaks toggling. `copy` + `del` worked fine for small files but it's too slow for toggling something large that a move could do instantly.

```
[*exeFS Patches]
filter_on /atmosphere/exefs_patches/.offload/
source_on /atmosphere/exefs_patches/*/
mkdir /atmosphere/exefs_patches/.offload/
move {source_on} /atmosphere/exefs_patches/.offload/

source_off /atmosphere/exefs_patches/.offload/*/
move {source_off} /atmosphere/exefs_patches/
```

**Comment by ppkantorski** [comment]
hmm, ill dive into it.  right now it will delete the destination file before moving.  let me see what else i need to modify in the move code.

**Comment by ppkantorski** [comment]
the only time move will move something to a directory is when it is a file and the filename is not specified.  otherwise it will try to write whatever you're working with to become the new directory.

**Comment by ppkantorski** [comment]
alright Mod Master 0.3.9 has this fix now.  hope that it makes more sense to you now
