### ISSUE TITLE
Question about other ovl in Ultrahand？

### ISSUE THREAD

**Issue by sskyNS** [ppkantorski/Ultrahand-Overlay#8]
Hello, how can I delete the version number of other ovl plug-ins of Tesla/Ultrahand overlay?

**Comment by ppkantorski** [comment]
You can overwrite the version of any overlay by using `hex-by-string`.  Something like this.
```hex-by-string <ovl_file_path> <version_to_replace> <version_replacement>```

If you have any more questions just lmk.

**Comment by ppkantorski** [comment]
hide_overlay_versions and hide_package_versions are now true or false options within /config/ultrahand/config.ini. 😊

**Comment by sskyNS** [comment]
here! I would like to ask again, how to remove the separators in Tesla's other plug-ins, such as emuiibo or fpslocker, the separators between their options are a bit annoying to me

**Comment by ppkantorski** [comment]
That needs to be done within libTesla during compilation for those overlays.  Overlays would need to be built with libTesla with those modifications. So it's kind of up to devs or the creator of libTesla unfortunately.

**Comment by ppkantorski** [comment]
Random thought... perhaps this specific color can be hexed directly into the .ovl? 🤔

**Comment by ppkantorski** [comment]
![Screenshot 2023-10-12 at 5 12 03 PM](https://github.com/ppkantorski/Ultrahand-Overlay/assets/6467366/ec9ca797-183b-4eb5-a4cf-827bb0c0aa5c)
Ok!  So if you hex search `77F7` and change it to `0000` it will change the separators into transparent.  I'll need to play with this in ultrahand.

**Comment by sskyNS** [comment]
Great. I also did a recompile test yesterday, which took effect. Thank you for providing more methods and ultrahand.

**Comment by ppkantorski** [comment]
so i think that if we use hex by custom offset on with hex `7F4300` as our offset, it may allow us to find the correct location for `77F7` every time. trying to think through how this can be scaled in both directions.  may need to rewrite a couple things, ill keep playing with it.

**Comment by ppkantorski** [comment]
Needs testing, but im sure that it can be found and replaced.  FPSLocker for instance appears to keep 77F7 stored right after that particular offset.  Same for Ultrahand.  But i will need to look more into those other overlays.  At the end of the day, unless they modified the color themselves within libTesla, we should be able to find and replace it.
![Screenshot 2023-10-12 at 5 56 01 PM](https://github.com/ppkantorski/Ultrahand-Overlay/assets/6467366/40410679-d2cf-4715-b049-13b1a0ae4a40)

**Comment by ppkantorski** [comment]
so it appears you can find it with ```77 F7 20 F2``` adding ```20 F2``` to the end, which means we have more to search ti by.  still scanning for potential offsets

**Comment by ppkantorski** [comment]
yes so changing to ```77 F7 20 F2``` ```77 00 20 F2``` will keep it unique, but make it fully transparent.  ill test on more overlays, appears to work.

**Comment by sskyNS** [comment]
直接用十六进制编译ovl似乎比修改tesla（listitem）要方便得多。基于任天堂的原始ui设计，队伍之间存在界限，修改变得更加简单、更加统一。Waiting for me to turn on the computer next time, I will try some ovl. In fact, I often use the hexadecimal system to complete some editing.

**Comment by ppkantorski** [comment]
im testing ovlEdizon.ovl, its not finding 77F7, but it is finding F777.  ill modify and see if its just flipping from big to little endian for some reason.

**Comment by ppkantorski** [comment]
no perhaps the value used to be differnt in older versions of libTesla.

**Comment by sskyNS** [comment]
If the change is based on Tesla, modifying the color frame should be able to complete the modification. But we need to modify each plug-in (in order to correspond to the functions you added before, I think we have hidden the line of ovlmenu, and we should also need to do other hiding, such as the one discussed now). If the hexadecimal modification cannot complete the unified modification of the old version, then it can Recompile it with the new version of tesla.hpp

**Comment by ppkantorski** [comment]
so some overlays by Tesla creator did not even use libTesla and have color representations in rgba8888.  This can still be replaced, should be unique.  If someone did something weird and didnt use libTesla for their overlay, it may have problems yeah.  But this could be controlled from the main menu via hex edit under the new settings page Im implementing.  Or someone could run a single command and replace all overlays with specific colors.  Should be doable, but it does depend on how they built their project.  Most overlays just use libTesla.

![Screenshot 2023-10-12 at 6 57 51 PM](https://github.com/ppkantorski/Ultrahand-Overlay/assets/6467366/3aa49933-aedd-4b40-b990-63832cde7cd8)

**Comment by sskyNS** [comment]
https://github.com/XorTroll/emuiibo
Simply try the modification of emuiibo to see if it can modify its line transparency in hexadecimal. If you have time, you can help me test it. I think he added a lot of original modifications, so that I can't find its color code. But I haven't tried the hexadecimal modification. Can you test it for me?

**Comment by ppkantorski** [comment]
Im looking through it, yeah he for some reason did not just cite the color universally by reference.  he made a habit of constantly redefining it in many locations (at least from inspection of the hex.). let me look into it more.

**Comment by ppkantorski** [comment]
https://github.com/search?q=repo%3AXorTroll%2Femuiibo%20ColorFrame&type=code Actually this is where he calls on ColorFrame.

**Comment by ppkantorski** [comment]
My suspicions right now are that ColorFrame was modified in his compilation.  i didnt try building it myself though

**Comment by sskyNS** [comment]
Yes, I'm not sure how to modify it, even if I know where his source code is. It doesn't look like the regular RGB color change code. Have you tried the hexadecimal system? Can you find and change it?

**Comment by ppkantorski** [comment]
I tried replacing 77F7 everywhere but it doesnt change it.  he might have changed the transparency value or something on his tesla fork

**Comment by sskyNS** [comment]
If there is nothing you can do, then I think I can give up and change it. Even this may drive people with obsessive-compulsive disorder crazy.

**Comment by ppkantorski** [comment]
if you are building it you can try replacing this value.  im not sure if it will change the color, but its worth trying. https://github.com/search?q=repo%3AXorTroll%2Femuiibo++0xF222&type=code

**Comment by ppkantorski** [comment]
overall, there is a way to modify libTesla.  But how people choose to draw their frames and colors can vary.  we can still cover a vast majority of projects with hexing though.  i'd say an improvement to libTesla to load colors externally would be a better approach overall, but it is possible to get it to look the same way for all of your overlays if you put enough time into it.

**Comment by sskyNS** [comment]
`renderer->drawRect(tsl::cfg::FramebufferWidth - 1, 0, 1, tsl::cfg::FramebufferHeight, a(0xF222));`
I have modified the rest of the coverage, and only this emuiibo is left. I will try what you said later and change this code to test it.

**Comment by ppkantorski** [comment]
what you may have to do is check each `renderer->drawRec` and perhaps change ColorFrame in libTesla. if thats not the correct one.  but its the color called when drawing the rectangle that creates the separator line yo usee

**Comment by sskyNS** [comment]
I briefly checked his source code, and it involves not many color modifications (in teslaextra.hpp) and testing should not be troublesome. If the change is correct.

**Comment by sskyNS** [comment]
Sorry, I may be disappointing you. My major is not programming. I may need to consult professional people, such as the original builder werwolv, but this code has been released for a long time. Unused references have added their own language, so he may not want to compare and modify it.

**Comment by ppkantorski** [comment]
i can maybe try building it myself.  i never use emumiibo personally.  all you would have to do is change the color value and rebuild to test.  but so far emumiibo appears to be the only one with this issue that ive seen

**Comment by sskyNS** [comment]
Indeed, my purpose is to maintain unity. Just like the questions I submitted here for the first time.

**Comment by sskyNS** [comment]
If possible, I hope you can help me or make a modified tesla for emuiibo, or other, respect

**Comment by ppkantorski** [comment]
im installing rust and cargo to build the overlay, ill just test it out really quuick.

**Comment by ppkantorski** [comment]
Here you go
[emuiibo.ovl.zip](https://github.com/ppkantorski/Ultrahand-Overlay/files/12889487/emuiibo.ovl.zip)

**Comment by sskyNS** [comment]
ths！It's my meal time now. I'll test it later and express my heartfelt thanks again.

**Comment by ppkantorski** [comment]
You should learn how to compile overlays, it will help if there are updates in the future.  Its not too hard to figure out, but it does take a little familiarizing.  That way you can guarantee that every overlay is customized to your likings.  It would be cool if libTesla was itself a universal binary that everyone can call upon, but it was made in a way that every project needs its own fork so modifications need to happen at the source.

**Comment by sskyNS** [comment]
If it's just a simple compilation, I will. But if I need to change some source code, such as this emuiibo and other very planned changes, I think I may still have to go a long way.

**Comment by sskyNS** [comment]
> a(tsl::style::color::ColorText));

For example, this is just a piece of text without standard RGB (0XFFFF), etc. This is the main reason for my difficulty.

**Comment by ppkantorski** [comment]
all that needed to change was ```            constexpr Color ColorFrame            = { 0x7, 0x7, 0x7, 0xF };   ///< Outer boarder color``` to ```            constexpr Color ColorFrame            = { 0x0, 0x0, 0x0, 0x0 };   ///< Outer boarder color``` really to make it transparent.  the last 0x0 is the transparency/alpha value

**Comment by ppkantorski** [comment]
btw, i can add a mode for "clean version" where it will only filter out the X.X.X from the version label and display it in that format no matter what the label version is.  i was thinking of adding it to make cleaner version labels something users can choose if they wanted.

**Comment by sskyNS** [comment]
I think this idea, while slight, is worth having. In addition, I basically understand the meaning of the color code. I already knew it before, and I used the same method to change the other plug-ins. Before you tell me that I can change fpslocker using hexadecimal, I compiled it with tesla and finished

**Comment by sskyNS** [comment]
[emuiibo.zip](https://github.com/ppkantorski/Ultrahand-Overlay/files/12891435/emuiibo.zip)
I guess the version may be different. It seems that he does not implement Tesla calls through ovl.

**Comment by sskyNS** [comment]
Because when opening this ovl in Tesla, the display is blank, so I guess it may be a version problem or something else.

**Comment by sskyNS** [comment]
Or based on my inference, some code may have been modified in the ovl you sent to make all the fonts disappear.

**Comment by ppkantorski** [comment]
i dont use it indepth, but its possible he used ColorFrame to define colors for other things other than the color frame.  however on mine all the text is there.  Im not using Tesla though.

**Comment by ppkantorski** [comment]
I made a new config.ini option ```clean_version_labels``` that can be set to `true` if you want to have all the versions displayed in a uniform format.  I'll add it to the next release.  almost done with v1.3.9

**Comment by sskyNS** [comment]
> 我没有深入使用它，但他可能使用 ColorFrame 来定义颜色框以外的其他事物的颜色。但是在我的身上，所有的文字都在那里。不过我没有使用特斯拉。
Can you upload a screenshot so I can see it, does emuiibo display text on your machine? Is it his latest release?

**Comment by sskyNS** [comment]
> I made a new config.ini option that can be set to if you want to have all the versions displayed in a uniform format. I'll add it to the next release. almost done with v1.3.9`clean_version_labels``true`

How does the current configuration differ from his? It seems that their version numbers can be hidden in config
