### ISSUE TITLE
not any issue more feedback 

### ISSUE THREAD

**Issue by carr654** [ppkantorski/Ultrahand-Overlay#93]
would like the ability to put a stock button in commands with shut down and reboot. currently i use studious just for the stock button so would be nice for of it all to be together

**Comment by ppkantorski** [comment]
what is the stock button exactly?  also, you can add any command you want to the package.ini's.  typically user system commands can be placed within `/switch/.packages/package.ini`

**Comment by carr654** [comment]
> you can add any command you want to the package.ini's. typically user system commands are placed within `/switch/.packages/package.ini`
> 
> you can add a command to isolate a reboot as follows
> 
> ```ini
> [Reboot to <NAME_OF_BOOT_ENTRY>]
> reboot boot <NAME_OF_BOOT_ENTRY>
> ```
> 
> or
> 
> ```ini
> [Reboot to <NAME_OF_INI_ENTRY>]
> reboot ini <NAME_OF_INI_ENTRY>
> ```
> 
> where the entry name is the name between `[` and `]` within the hekate bootloader ini files (the name for the entry that is displayed on the Hekate menu). The name for this command can be whatever you want, but the commands must be `reboot ini ...` or `reboot boot ...`.

so stock is use for online gaming i have a dual nand set up. this is what my entry in my hekate ipl looks like in it - whats the exact command i need to put to get this to show with the reboot and shut down. so im assuming it would be. what should be the entry i put in the command for such function. the set up is quite confusing on how to add commands yourself the others im okay that was easy. 

[Stock]
emummc_force_disable=1
fss0=atmosphere/package3
stock=1
icon=bootloader/res/icon_stock.bmp

**Comment by carr654** [comment]
> you can add any command you want to the package.ini's. typically user system commands are placed within `/switch/.packages/package.ini`
> 
> you can add a command to isolate a reboot as follows
> 
> ```ini
> [Reboot to <NAME_OF_BOOT_ENTRY>]
> reboot boot <NAME_OF_BOOT_ENTRY>
> ```
> 
> or
> 
> ```ini
> [Reboot to <NAME_OF_INI_ENTRY>]
> reboot ini <NAME_OF_INI_ENTRY>
> ```
> 
> where the entry name is the name between `[` and `]` within the hekate bootloader ini files (the name for the entry that is displayed on the Hekate menu). The name for this command can be whatever you want, but the commands must be `reboot ini ...` or `reboot boot ...`.

ok no i have no clue how to get a stock button working. it just boots to hekate where as i want it to boot straight to stock bypassing having to select it in hekate menu like i can with studious pancake. im so confused how to config this. sorry for bugging you with this. i dont suppose you can help me with this, i would be greatly appriaciated. my hekate ipl.ini looks like this. i just dont understand how to put this into the package ini. 

[config]
autoboot=0
autoboot_list=0
bootwait=3
backlight=154
noticker=0
autohosoff=0
autonogc=1
updater2p=0
bootprotect=0

[Atmosphere CFW]
payload=bootloader/payloads/fusee.bin
icon=bootloader/res/icon_payload.bmp 

[Stock]
emummc_force_disable=1
fss0=atmosphere/package3
stock=1
icon=bootloader/res/icon_stock.bmp

**Comment by ppkantorski** [comment]
```[Stock Reboot]
reboot boot Stock```

**Comment by carr654** [comment]
> ```ini
> [Stock Reboot]
> reboot boot Stock
> ```

works perfectly, i can see where i was going wrong now thank you for that
